feat(charts): add option to configure revisionHistoryLimit to subcharts
acryldata/datahub-helm pull request #159
Opened 2022-09-01 16:14 UTC by bskim45

This PR adds the ability for end-users to configure `revisitonHistoryLimit` for the deployments of subcharts.

In addition, bumps chart version to 0.2.93

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2022-09-02 07:38 UTC, szalai1 approved these changes
Thanks for adding this. LGTM

2022-09-02 07:41 UTC, bskim45 commented
Rebumped chart version to 0.2.94

2022-09-09 14:32 UTC, bskim45 commented on charts/datahub/Chart.yaml
> +version: 0.2.94
```suggestion
version: 0.2.95
```

2022-09-10 01:56 UTC, anshbansal requested changes
As you have made changes in charts for both `datahub-frontend` as well as `datahub-gms` the versions for them also need to be increased by a minor version

2022-09-12 05:28 UTC, bskim45 commented
> As you have made changes in charts for both `datahub-frontend` as well as `datahub-gms` the versions for them also need to be increased by a minor version

done!

2022-09-12 10:31 UTC, anshbansal approved these changes
LGTM

2022-09-12 10:31 UTC, merged