feat: datahub-frontend add oidc authentication client secret reference
acryldata/datahub-helm pull request #165
Opened 2022-09-08 22:50 UTC by TonyOuyangGit

This PR adds an option to configure OIDC authentication client secret to refer to Kubernetes Secrets. The deployment YAML will retrieve `AUTH_OIDC_CLIENT_SECRET` from Kubernetes Secrets if `datahub-frontend.oidcAuthentication.clientSecretRef` and `datahub-frontend.oidcAuthentication.clientSecretKey` is present This is also backward compatible with the existing `datahub-frontend.oidcAuthentication` config.

Local testing has been done through rendering using `helm template . > preview.yaml.`

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2022-09-09 17:50 UTC, jinlintt commented on charts/datahub/subcharts/datahub-frontend/README.md
> +| oidcAuthentication.clientSecret.secretKey | string | `"nil"` | Optional, this is the key of the shared secret to use for exchange between you and your identity provider |
This should be `oidcAuthentication.clientSecretRef.secretKey`

2022-09-09 17:54 UTC, jinlintt commented on charts/datahub/Chart.yaml
> +appVersion: 0.8.45
We don't need to bump the `appVersion` since the app isn't changed.

2022-09-09 17:54 UTC, jinlintt commented on charts/datahub/subcharts/datahub-frontend/Chart.yaml
> +appVersion: 0.3.4
Ditto

2022-09-09 18:23 UTC, jinlintt approved these changes
LGTM, please wait until @jjoyce0510 or someone else from the DH team has a chance to review as well.

2022-09-10 01:49 UTC, anshbansal commented
The chart version needs to be increased by a minor version in `charts/datahub/Chart.yaml`

2022-09-10 01:51 UTC, anshbansal requested changes
The chart version needs to be increased by a minor version in charts/datahub/Chart.yaml

2022-09-12 17:15 UTC, anshbansal approved these changes
LGTM

2022-09-12 17:15 UTC, merged