fix(datahub-frontend): Remove unused env var
acryldata/datahub-helm pull request #176
Opened 2022-09-21 20:32 UTC by pedro93

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

2022-09-22 01:04 UTC, RyanHolstien approved these changes

2022-09-22 05:30 UTC, anshbansal requested changes
The main Chart version needs to be updated from `0.2.105` to `0.2.106`

2022-10-11 11:40 UTC, szalai1 approved these changes

2022-10-11 14:39 UTC, szalai1 approved these changes

2022-10-11 14:44 UTC, merged