feat(sql): extend username/password configuration
acryldata/datahub-helm pull request #198
Opened 2022-11-15 16:30 UTC by CallumREdwards

## Overview 
This PR extends the existing configuration for the SQL database in two ways:

1. Allows the SQL set-up jobs to run using a different username and password to that used by the GMS. This allows users to specify a login account with a more permissive set of permissions for the set-up jobs (which requires essentially owner perms) than the logic account used by the GMS (which only requires traditional read-write perms).
2. Allows specifying the login password for the SQL backings using a string value. This is specifically important for users interacting with vault manipulating webhooks to inject their vault-saved credentials, which does pair nicely with using k8s secrets.

This PR is backwards compatible to existing configuration approach (importantly not changing any of the default values).

## Example Use
The values file can contain something like this:
```
datahub-gms:
  sql:
    datasource:
      username: "User 1"
      password:
        value: "string that will be used by webhook"
```
and 
```
postgresqlSetupJob:
  enabled: true
  username: "User 2"
  password:
    value: "a different string that will be used by webhook"
```
which will mean that the gms will be logged in as 'User 1' using a password injected by a webhook, and the set-up job will be logged in as 'User 2' using a different injected password.

## Checklist
- [✔️] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [✔️] Links to related issues (if applicable)
- [✔️ ] Tests for the changes have been added/updated (if applicable)
- [✔️] Docs related to the changes have been added/updated (if applicable)

2022-11-15 16:36 UTC, CallumREdwards commented on charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
> +              value: "{{ .Values.sql.datasource.username | default .Values.global.sql.datasource.username }}"
The templating will attempt to use the deployment specific config but will fallback to the existing global config if not found for backwards compatibility.

2022-11-15 16:36 UTC, CallumREdwards commented on charts/datahub/subcharts/datahub-gms/templates/deployment.yaml
> +              {{- if $passwordValue }}
again, the value of a password will only be used if it has been set, otherwise it will attempt to use a k8s secret

2022-11-18 12:10 UTC, szalai1 requested changes
This looks good! Thanks for the contribution!

requests:
* could you add the new field to the README.md 
* could you add a commented out version of this to the values.yaml so people can know how to use it in practice?

2022-11-18 14:24 UTC, CallumREdwards commented
Thanks Peter - ready for another review!

2022-11-18 14:44 UTC, szalai1 commented
you need to bump the versions:
* in the subchart 
* in the high level chart's reference to the subchart
* highlevel chart version

2022-11-18 15:59 UTC, szalai1 commented
thanks @CallumREdwards TIL about using `()` for `nil` testing.

2022-11-18 15:59 UTC, szalai1 approved these changes

2022-11-21 10:12 UTC, merged