fix(registry): Revert default schema registry to Confluent's Schema Registry
acryldata/datahub-helm pull request #349
Opened 2023-08-10 13:37 UTC by pedro93

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2023-08-10 13:44 UTC, shirshanka requested changes

2023-08-10 13:44 UTC, shirshanka commented on charts/datahub/values.yaml
> +        url: "http://prerequisites-cp-schema-registry:8081"
Indent?

2023-08-10 13:55 UTC, pedro93 commented on charts/datahub/values.yaml
> +        url: "http://prerequisites-cp-schema-registry:8081"
Yes, good catch

2023-08-27 02:11 UTC, david-leifker approved these changes

2023-11-19 01:50 UTC, closed without merging